graphs/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'wordcount', views.WordCountViewSet)


urlpatterns = [
    url(r'api/', include(router.urls, namespace="api")),
    url(r'^$', views.index, name="index"),
    url(r'token/', views.token, name="token"),
    url(r'clientscript\.sh$', views.client_script, name="client_script"),
    url(r'count', views.count, name="count")
]

thesisometer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from .views import GraphsRedirectView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', GraphsRedirectView.as_view(), name='registration_register'),
    url(r'^accounts/register/closed/$', TemplateView.as_view(template_name='registration/registration_closed.html'),
                          name='registration_disallowed'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^", include('graphs.urls', namespace='graphs'))
]

graphs/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Create your models here.


class WordCount(models.Model):
    count = models.IntegerField(default=0)
    date = models.DateField(default=datetime.date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="counts")

    def save(self, *args, **kwargs):
        try:
            self.validate_unique()
        except ValidationError:
            wc = WordCount.objects.filter(date=self.date, user=self.user).first()
            wc.count = self.count
            wc.save()
            return
        super(WordCount, self).save(*args, **kwargs)


    class Meta:
        unique_together = ("date", "user")

graphs/forms.py
from django import forms

from .models import WordCount


class WordCountForm(forms.ModelForm):

    class Meta:
        model = WordCount
        fields = "count",

thesisometer/forms.py
from registration.forms import RegistrationForm


class NoEmailRegistrationForm(RegistrationForm):

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields.pop('email')

graphs/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from rest_framework import permissions
from rest_framework import status
from rest_framework import viewsets
from rest_framework.authtoken.models import Token
from rest_framework.response import Response

from .serializers import UserSerializer, WordCountSerializer
from .forms import WordCountForm
from .models import WordCount

# Create your views here.


def index(request):
    form = WordCountForm()
    return render(request, 'graphs/index.html', {"form": form})


@login_required
def count(request):
    if request.method == "POST":
        form = WordCountForm(request.POST)
        if form.is_valid():
            wc = form.save(commit=False)
            wc.user = request.user
            wc.save()
            return redirect('graphs:index')
    else:
        return redirect('graphs:index')

@login_required
def token(request):
    u_token = Token.objects.get_or_create(user=request.user)
    return render(request, 'graphs/token.html', {'token': u_token[0].key})


@login_required
def client_script(request):
    u_token = Token.objects.get_or_create(user=request.user)
    return render(request, 'graphs/thesis_graph.sh', {'token': u_token[0].key, 'host': request.get_host()},
                  content_type="text/plain  ")


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by("-username")
    serializer_class = UserSerializer
    http_method_names = ['get', 'head', 'options']


class WordCountViewSet(viewsets.ModelViewSet):
    queryset = WordCount.objects.all()
    serializer_class = WordCountSerializer
    permission_classes = permissions.IsAuthenticatedOrReadOnly,

    def create(self, request):
        serializer = WordCountSerializer(data=request.data)
        if serializer.is_valid():
            wc = serializer.save(user=request.user)
            wc.save()
            return Response(status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

thesisometer/views.py
from registration.backends.simple.views import RegistrationView
from .forms import NoEmailRegistrationForm
from django.urls import reverse


class GraphsRedirectView(RegistrationView):
    form_class = NoEmailRegistrationForm

    def get_form_class(self):
        return NoEmailRegistrationForm

    def get_success_url(self, user):
        return reverse("graphs:index")

graphs/templates/graphs/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "graphs/css/metricsgraphics.css" %}" >
    <link rel="stylesheet" type="text/css" href="{% static "graphs/css/graphs.css" %}" >
{% endblock %}

{% block content %}
    <div id="chart"></div>
    <div id="date_range">
        <form id="date_range_form">
            <div class="radios" >
                <div class="radio_group" >
                    <label for="range_all">All</label>

                        <input type="radio" name="range" id="range_all" value="all" checked />
                </div>

                <div class="radio_group">
                    <label for="range_year">Past year</label>
                    <input type="radio" name="range" id="range_year" value="year"/>
                </div>

                <div class="radio_group">
                    <label for="range_quarter">Past quarter</label>
                    <input type="radio" name="range" id="range_quarter" value="quarter"/>
                </div >

                <div class="radio_group">
                    <label for="range_month">Past month</label>
                    <input type="radio" name="range" id="range_month" value="month"/>
                </div>
            </div>
        </form>
    </div>

    {% if user.is_authenticated %}
        <div id="formblock">
            <h2>Update Wordcount</h2>
            <form id="count_form" action="{% url 'graphs:count' %}" method="post">{% csrf_token %}
                {{ form }}
                <button type="submit" class="save btn">Post</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="{% static "graphs/js/metricsgraphics.min.js" %}"></script>
    <script src="{% static "graphs/js/main.js" %}"></script>
{% endblock %}

graphs/templates/graphs/token.html
{% extends "base.html" %}

{% block content %}
    Token: {{ token }}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Thesis-o-meter
        </title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static "thesisometer/main.css" %}">
        {% block head %}
        {% endblock %}
        {% block title %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar" >
            <ul class="navlist">
                <li><a href="{% url "graphs:index" %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url "auth_logout" %}">Logout</a></li>
                    <li><a href="{% url "graphs:client_script" %}">Bash Script</a></li>
                {% else %}
                    <li><a href="{% url "auth_login" %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
        <div class="container">

            <div id="main" role="main">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    {% block scripts %}
    {% endblock %}
    </body>
</html>